
V = 0
Q = $(if $(filter 1,$V),,@)

.EXPORT_ALL_VARIABLES:

GOPRIVATE=github.com/\!iotic-\!labs/*
GOPROXY=https://nexus.cor.corp.iotic/repository/go-proxy/
GONOSUMDB=github.com/Iotic-Labs

build:
	go build .
